Thoughtmuseum/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Thoughtmuseum import settings
from thoughtmuseum_app import views, meetings_views, resources_views, reminder_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.dashboard, name='dashboard'),
    #temporary commented
    #path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),    
    path('meetings/', meetings_views.meetings, name='meetings'),
    path('meetings/scheduler/', meetings_views.scheduler, name='scheduler'),
    path('delete_meeting/', meetings_views.delete_meeting, name='delete_meeting'),
    path('calendar/', views.calendar, name='calendar'),
    path('get_calendar/', views.get_calendar, name='get_calendar'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('contact/', views.contact, name='contact'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('my_courses/', views.my_courses, name='my_courses'),
    path('my_courses/classpage/', views.classPage, name='classpage'),
    path('flexiquiz-webhook/', views.flexiquiz_webhook),
    path('select_user/<int:user_id>', views.select_user, name='select_user'),
    path('resources/', resources_views.resources_overview, name='resources'),
    path('resources-upload/', resources_views.upload, name='upload'),
    path(r'logout/', views.logout,  name='logout'),
    path('reminder/', reminder_views.reminder, name='reminder'),
    url(r'^resources/(?P<slug>[^//]*)$', resources_views.resources_overview_second_level,
        name="resources_overview_second_level"),
    url(r'^resources/(?P<slug>.*)$', resources_views.resources_index,
        name="resources_index"),
    url('avatar/', include('avatar.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

thoughtmuseum_app/models.py
from django.db import models
from django.contrib.auth.models import User
import pytz
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils import timezone
import datetime

REMINDER_TIME = (
        ('15', 15),
        ('30', 30),
        ('60', 60)        
    )
def get_first_name(self):
    return self.first_name

def get_name(self):
    return '{} {}'.format(self.first_name, self.last_name)

User.add_to_class("__str__", get_name)

class Timezone(models.Model):
    tzs = list(pytz.all_timezones_set)
    tzs.sort(key=str.lower)
    MY_CHOICES = tuple((str(idx), str(n)) for idx, n in enumerate(tzs))
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    timezone = models.CharField(max_length=35, choices=MY_CHOICES)

    def __str__(self):
        return self.timezone
    
    def get_timezone(self):
        return pytz.timezone(Timezone.MY_CHOICES[int(self.timezone)][1])


class TeacherProfile(models.Model):
    user = models.OneToOneField(User, related_name='teacher', on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True, default='')
    specialization = models.CharField(max_length=250, )
    highest_degree_earned = models.CharField(max_length=50, )
    address = models.TextField(max_length=250, )
    website = models.CharField(max_length=50, blank=True, default='')
    publications = models.CharField(max_length=250, blank=True, default='')
    photo = models.CharField(max_length=250, blank=True, default='')
    phone_number = models.CharField(max_length=250, )
    zoom_host_user_id = models.CharField(max_length=50, blank=True, default='')

    # This is the name in main admin overview of all registered Models
    class Meta:
        verbose_name = "Teacher Profile"
        verbose_name_plural = 'Teacher Profiles'

    # This changes the title of the Meetings object 
    def __str__(self):
        title = 'Profile of ' + str(self.user)
        return title

STUDENT_GENDER=(('M', 'Male'),
                ('F', 'Female'))

class CustomerProfile(models.Model):
    user = models.OneToOneField(User, related_name='customer', on_delete=models.CASCADE,   limit_choices_to={'groups__name': u'customer'},)
    date_of_birth = models.DateField()   
    student_gender = models.CharField(max_length=1, choices=STUDENT_GENDER, blank=True, default='')
    grade_level = models.CharField(max_length=250, )
    semester = models.CharField(max_length=128, blank=True, default='')
    school_year = models.CharField(max_length=32, blank=True, default='') 
    reminder_time = models.CharField(max_length=2, choices=REMINDER_TIME, default='60')       
    street_address = models.CharField(max_length=250, blank=True, default='')
    street_address_line_2 = models.CharField(max_length=250, blank=True, default='')
    city =  models.CharField(max_length=128, blank=True, default='')
    state =  models.CharField(max_length=128, blank=True, default='')
    zip_code =  models.CharField(max_length=128, blank=True, default='')
    phone_number = models.CharField(max_length=16, blank=True, default='')
    home_phone_number = models.CharField(max_length=16, blank=True, default='')
    # This is the name in main admin overview of all registered Models
    class Meta:
        verbose_name = "Customer Profile"
        verbose_name_plural = 'Customer Profiles'

    # This changes the title of the Meetings object 
    def __str__(self):
        title = 'Profile of ' + str(self.user)
        return title


class ParentProfile(models.Model):
    user = models.OneToOneField(User, related_name='parent',
                                on_delete=models.CASCADE,
                                limit_choices_to={'groups__name': u'parent'},)
    children = models.ManyToManyField(User, limit_choices_to={'groups__name': u'customer'})
    street_address = models.CharField(max_length=250, blank=True, default='')
    street_address_line_2 = models.CharField(max_length=250, blank=True, default='')
    city =  models.CharField(max_length=128, blank=True, default='')
    state =  models.CharField(max_length=128, blank=True, default='')
    zip_code =  models.CharField(max_length=128, blank=True, default='')
    phone_number = models.CharField(max_length=16, blank=True, default='')
    selected_child = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE, related_name='_selected_child')
    reminder_time = models.CharField(max_length=2, choices=REMINDER_TIME, default='60')

    def __str__(self):
        return 'Profile of ' + str(self.user)

def get_teacher():
    teachers = User.objects.filter(groups__name='teacher')
    if teachers:
        return teachers[0]
    return None

class Meeting(models.Model):
    teacher = models.ForeignKey(User, on_delete=models.PROTECT,
                                related_name='meeting_origin',
                                limit_choices_to={'groups__name': u'teacher'},
                                default=get_teacher)
    student = models.ForeignKey(User, on_delete=models.PROTECT,
                                related_name='meeting_target',
                                limit_choices_to={'groups__name': u'customer'},
                                default='0')
    student2 = models.ForeignKey(User, on_delete=models.PROTECT,
                                 related_name='meeting_target2',
                                 limit_choices_to={'groups__name': u'customer'},
                                 blank=True, null=True)
    student3 = models.ForeignKey(User, on_delete=models.PROTECT,
                                 related_name='meeting_target3',
                                 limit_choices_to={'groups__name': u'customer'},
                                 blank=True, null=True)
    student4 = models.ForeignKey(User, on_delete=models.PROTECT,
                                 related_name='meeting_target4',
                                 limit_choices_to={'groups__name': u'customer'},
                                 blank=True, null=True)
    student5 = models.ForeignKey(User, on_delete=models.PROTECT,
                                 related_name='meeting_target5',
                                 limit_choices_to={'groups__name': u'customer'},
                                 blank=True, null=True)
    meeting_time = models.DateTimeField(default=timezone.now, blank=True)
    meeting_date = models.DateField(default=timezone.now)
    setup_time = models.DateTimeField(default=timezone.now, blank=True)
    start_url = models.TextField(blank=True)
    join_url = models.CharField(max_length=100, blank=True)
    topic = models.CharField(max_length=100, blank=True)
    meeting_password = models.CharField(max_length=32, null=True, blank=True)
    meeting_id = models.CharField(max_length=16, null=True, blank=True)
    duration = models.IntegerField(default=60)

    # This is the name in main admin overview of all registered Models
    class Meta:
        verbose_name = "Meeting"
        verbose_name_plural = 'Meetings'

    # This changes the title of the Meetings object
    def __str__(self):
        title = str(self.teacher) + ' with ' + str(self.student)
        if self.student2 or self.student3 or self.student4 or self.student5:
            title = title + ' +'
        return title

    def meeting_end_time(self):
        return self.meeting_time + datetime.timedelta(days=0, hours=0, minutes=self.duration)

    def get_students_name(self):
        name = self.student.get_full_name()
        if self.student2:
            name += ", " + self.student2.get_full_name()
        if self.student3:
            name += ", " + self.student3.get_full_name()
        if self.student4:
            name += ", " + self.student4.get_full_name()
        if self.student5:
            name += ", " + self.student5.get_full_name()
        return name

    def get_students_first_name_for_parent(self, parent):
        name = ''    
        if self.student in parent.children.all():
            name += self.student.first_name
        if self.student2 in parent.children.all():
            if len(name) > 1:
                name += ', '
            name += " " + self.student2.first_name
        if self.student3 in parent.children.all():
            if len(name) > 1:
                name += ', '
            name += " " + self.student3.first_name
        if self.student4 in parent.children.all():
            if len(name) > 1:
                name += ', '
            name += " " + self.student4.first_name
        if self.student5 in parent.children.all():
            if len(name) > 1:
                name += ', '
            name += " " + self.student5.first_name
        return name

    def get_more_students(self):
        name = ''
        if self.student2:
            name += self.student2.username
        if self.student3:
            name += ", " + self.student3.username
        if self.student4:
            name += ", " + self.student4.username
        if self.student5:
            name += ", " + self.student5.username
        return name

    def get_meeting_id(self):
        if self.meeting_id:
            return self.meeting_id
        s = self.join_url.split("/")
        return s[-1].strip()

    def get_meeting_date_time_for_the_user_time_zone(self, user):
        fmt_date = '%a, %B %d %Y'
        fmt_time = '%I:%M %p'
        tz = Timezone.objects.get(user=user).get_timezone()

        meeting_datetime = self.meeting_time.astimezone(tz)
        meeting_datetime = u'{} {}'.format( meeting_datetime.time().strftime(fmt_time), meeting_datetime.date().strftime(fmt_date))
        return meeting_datetime, tz

    def get_meeting_time_for_the_user_time_zone(self, user):
        fmt_time = '%I:%M %p'
        tz = Timezone.objects.get(user=user).get_timezone()

        meeting_datetime = self.meeting_time.astimezone(tz)
        meeting_datetime = u'{}'.format(meeting_datetime.time().strftime(fmt_time))

thoughtmuseum_app/templates/calendar.html
{% extends "index.html" %}
{% load static %}

{% block extra_head %}
	<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">	
	<link href="{% static 'calendar/core/main.min.css' %}" rel="stylesheet" />
	<link href="{% static 'calendar/daygrid/main.min.css' %}" rel="stylesheet" />
	<link href="{% static 'calendar/timegrid/main.min.css' %}" rel="stylesheet" />
	<link href="{% static 'calendar/list/main.min.css' %}" rel="stylesheet" />
	<link href="{% static 'calendar/bootstrap/main.min.css' %}" rel="stylesheet" />
	<script src="{% static 'calendar/core/main.min.js' %}"></script>
	<script src="{% static 'calendar/interaction/main.min.js' %}"></script>
	<script src="{% static 'calendar/daygrid/main.min.js' %}"></script>
	<script src="{% static 'calendar/timegrid/main.min.js' %}"></script>
	<script src="{% static 'calendar/list/main.min.js' %}"></script>
	<script src="{% static 'calendar/bootstrap/main.min.js' %}"></script>	
{% endblock %}


{% block content %}

<section id="meetings" >
	<div class="container">
		<div class="row">			
			<div class='col-12 section-title'>
				<h3>Calendar</h3>	
				{% if isScheduler %}
					<p id='scheduler_title'> Note times refer to teacher's and student's timezone.</p>
				{% else %}
					<p> Note that all times refer to your timezone.</p>
					<p> Your timezone is: {{ timezone }} </p>
				{% endif %}					
			</div>			
		</div>
		<hr/>		
		{% if isScheduler %}
			<section class="light" style="padding:0px" id="scheduler">
				<form method="post" class="form-horizontal" id="scheduler-form">
					{% csrf_token %}
					<div class="row form-group">				
						<label for="id_teacher" class="col-sm-1 control-label label_search_calendar">Teacher:</label>
						<div class="col-sm-4 controls">
							{{ calendarSearch.teacher }}
						</div>	
				
						<label for="id_student" class="col-sm-1 control-label label_search_calendar">Student:</label>
						<div class="col-sm-4 controls">
							{{ calendarSearch.student }}
						</div>				
									
						<div class="col-sm-2">				
							<button type="submit" class="btn-outline btn btn-default" id="searchBtn">
								<span class="glyphicon glyphicon-search" style="margin-right: 8px;" aria-hidden="true"></span>
								Search
							</button>				
						</div>						
					</div>
				</form>	
			</section>
			<hr/>
		{% endif %}
		<div id="calendar"></div>		
	</div>
</section>

	<script>
		document.addEventListener('DOMContentLoaded', function() {
			var calendarEl = document.getElementById('calendar');

			var calendar = new FullCalendar.Calendar(calendarEl, {
				plugins: [ 'bootstrap', 'dayGrid', 'timeGrid', 'list', 'interaction' ],
				themeSystem: 'bootstrap',
				header: {
					left: 'prev,next today',
					center: 'title',
					right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
				},     
				navLinks: true, 
				editable: true,
				eventLimit: true, 
				eventRender: function (info) {
					$(info.el).tooltip({ title: info.event.title });     
				},	  
				displayEventTime: false,			
				timeZone: '{{ timezone }}',
				events:{
					url: "{% url 'get_calendar' %}",
					type: 'GET',
					extraParams: {
        				teacher_id: $('#id_teacher').val(),
						student_id: $('#id_student').val()
      				},				
				},
			});

			calendar.render();
		});
	</script>	
	{% if isScheduler %}
		<script>
		
			function set_title(){
				var title  = $('.fc-center h2').text();
				const additional_text = ' (PST)';
				if (!title.includes(additional_text))
					$('.fc-center h2').html($('.fc-center h2').text() + additional_text);
			}

			function set_title_click(){
				$('.fc-dayGridMonth-button').click(set_title);
				$('.fc-timeGridWeek-button').click(set_title);
				$('.fc-timeGridDay-button').click(set_title);
				$('.fc-listWeek-button').click(set_title);
			};

			$(document).ready(function(){
				$("body").on('DOMSubtreeModified', ".fc-center", set_title_click);
				set_title_click();
				set_title();
			});			
		</script>
	{% endif %}
	
{% endblock %}

thoughtmuseum_app/templates/contact.html
{% extends "index.html" %}
{% load static %}


{% block content %}

<!-- Header -->
<header id="dashboard">
	<div class="container">
		<div class="row text-center">
			<div class="col-12">
				<p>Contact Us</p>
			</div>
		</div>
		{% if msg %}
		<div class="row text-center">
			<div class="col-12">
				<span class="h3 text-danger">{{msg}}</span>
			</div>
		</div>
		{% endif %}
	</div>
</header>

<section id="contact">
	<div class="container">
		<div class="row">
			<div class="col-6">
                <div class="contact-col-wrap-l">
                    <p>We would love to hear from you! Please fill out the form and one of our team members will contact you as soon as possible.</p>                    
                </div>
			</div>
			<div class="col-6">
                <div class="contact-col-wrap-r">
					<form method="post">
						{% csrf_token %}
						<div class="form-group">
							<label class="control-label">NAME</label>
							<div class="controls">
								<div class="form-inline">
									{{ form.first_name }}									
								</div>
							</div>							
						</div>
						<div class="form-group">
							<div class="form-inline">
								{{ form.last_name }}
							</div>
						</div>
						<div class="form-group">
							<label class="control-label">EMAIL</label>
							{{form.email}}
						</div>
						<div class="form-group">
							<label class="control-label">PHONE</label>
							{{form.phone}}
						</div>
						<div class="form-group">
							<label class="control-label">COMMENTS</label>
							{{form.comments}}
						</div>
							<button type="submit" class="btn btn-danger form-control font-bold">SUBMIT</button>
					</form>
                </div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

thoughtmuseum_app/templates/dashboard.html
{% extends "index.html" %}
{% load static %}
{% load avatar_tags %}
{% load user_tags %}

{% block content %}

<!-- Portfolio Grid Section -->
<section id="dashboard">
	<div class="container">	
		<div class="row">
			<div class="col dash_col dash_animate"  onclick="location.href={% url 'my_courses'%}" style="cursor: pointer;"> 
				<div class="dash_extra " style="background-color: #1b67b8;" >
					<a href="{% url 'my_courses' %}" >
						<img src="{% static 'img/my_courses-100.png' %}" class="dash-img" alt="">
						<img src="{% static 'gif/my_courses.gif' %}" class="dash-img centered-element" alt="">
					 </a>	
					 <p class="dash_menu_text_color"> My courses</p>				 	
				</div>
			</div>

			<div class="col dash_col dash_animate"  onclick="location.href={% url 'resources'%}" style="cursor: pointer;">
				<div class="dash_extra " style="background-color: #3176c1;" >
					<a href="{% url 'resources' %}">
						<img src="{% static 'img/resources-100.png' %}" class="dash-img" alt="">
						<img src="{% static 'gif/resources.gif' %}" class="dash-img centered-element" alt="">
					 </a>	
					 <p class="dash_menu_text_color"> Resources</p>				 	
				</div>
			</div>

			<div class="col dash_col dash_animate"  onclick="location.href={% url 'meetings'%}" style="cursor: pointer;">
				<div class="dash_extra" style="background-color: #5190d3">
					<a href="{% url 'meetings'%}">
						<img src="{% static 'img/meetings-100.png' %}" class="dash-img" alt="">
						<img src="{% static 'gif/meetings.gif' %}" class="dash-img centered-element" alt="">												
					</a>
					<p class="dash_menu_text_color">Meetings</p>					  
				</div>
			</div>

			<div class="col dash_col dash_animate"  onclick="location.href={% url 'calendar'%}" style="cursor: pointer;">
				<div class="dash_extra" style="background-color: #66a3e4">
					<a href="{% url 'calendar'%}">
						<img src="{% static 'img/calendar-100.png' %}" class="dash-img" alt="">
						<img src="{% static 'gif/calendar.gif' %}" class="dash-img centered-element" alt="">						
					</a>
					<p class="dash_menu_text_color">Calendar</p>					  
				</div>
			</div>

			<div class="col dash_col dash_animate"  onclick="location.href={% url 'portfolio'%}" style="cursor: pointer;">
				<div class="dash_extra" style="background-color: #7fb7f2">
					<a href="{% url 'portfolio'%}">
						<img src="{% static 'img/portfolio-100.png' %}" class="dash-img" alt="">
						<img src="{% static 'gif/portfolio.gif' %}" class="dash-img centered-element" alt="">						
					</a>
					<p class="dash_menu_text_color">Portfolio</p>					  
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-8 about_you_dvi" onclick="location.href={% url 'my_profile'%}" style="cursor: pointer;">
				<div class="about_you_dvi_title">
					<div class="dash_div_title">
						About You
					</div>
					<div>
						<img src="{% static 'img/about_you_banner.png' %}" class="fill_div_by_img">
						<div class="about_you_img_text">
							{{ request.session.user_first_name }}
						</div>
					</div>
				</div>
				{% avatar request.session.avatar 120 class="rounded-circle img-thumbnail img-fluid about_you_img_avatar" id="user_avatar"  %}				
			</div>

			<div class="col-4 ml-auto upcoming_meetings_dvi">
				<div class="dash_div_title">
					Upcoming Meetings
				</div>
				<div class="dash_div_text">
					{{meeting_datetime}}
				</div>
				<div>
					<img src="{% static 'img/upcoming_meetings.png' %}" style="padding-top: 1em;">
				</div>
				<div class="dash_div_text">
					{{teacher_name}}
				</div>
			</div>
		</div>
	</div>
</section>
	

	
{% endblock %}	

thoughtmuseum_app/templates/index.html
{% load static %}
{% load avatar_tags %}
{% load user_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Thoughtmuseum</title>

	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/beecgo.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/custom2.css' %}">
	<link rel="stylesheet" href="{% static 'css/custom3.css' %}">
	<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/feather-icons"></script>
	

	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
{% block extra_head %}
{% endblock %}


</head>
	<body id="page-top">

		{% if request.user.is_authenticated %}
			<nav class="navbar navbar-expand-lg navbar-light fixed-top"> 
				<div class="container"> 
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMainMenu">
						<span class="navbar-toggler-icon"></span>
					</button>					
					<div class="collapse navbar-collapse" id="navbarMainMenu">
						<a class="navbar-brand" href="/">
							<img src="{% static 'img/logo.png' %}" alt="" width=150px height=90px>
						</a>
						<div class="navbar-nav ml-auto">
							<ul class="nav navbar-nav">
								<li><a class="nav-item nav-link menu_text_button" href="/">Dashboard</a></li>
								<li><a class="nav-item nav-link menu_text_button" href="#">Links</a></li>
								<li><a class="nav-item nav-link menu_text_button" href="{% url 'contact' %}">Contact Thoughtmuseum</a></li>
								<li><a class="nav-item nav-link menu_text_button"  href="{% url 'my_profile' %}">
									{% avatar  request.session.avatar 30 class="rounded-circle img-thumbnail img-fluid" id="user_avatar"  %}
									{{ request.session.user_first_name }}															
								</a>
							</li>
		
								<li style="padding-top: .9em !important;" class="dropdown">
									<a href="#"  class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label"></span> <span class="caret"></span></a>
									<ul class="dropdown-menu">										
										{% if request.user|has_group:"parent" %}
										<li><a class="nav-item nav-link menu_text_button" href="{% url 'select_user' user.id %}">Me</a></li>
											{% for ch in request.session.children %}
												<li><a class="nav-item nav-link menu_text_button" href="{% url 'select_user' ch.0 %}">{{ch.1}}</a></li>
											{% endfor %}
										{% endif %}									
										<li><a class="nav-item nav-link menu_text_button" href="{% url 'logout' %}"><i data-feather="log-out"></i> Logout</a></li>
									</ul>
								</li>
							</ul>
						</div>

					</div>
					

					
					

				</div>
			</nav>	  
		{% endif %}

		

{% block content %}
{% endblock %}	

{% block footer %}
{% endblock footer %}	

  

    <script>
      feather.replace()
    </script>
  </body>
</html>

thoughtmuseum_app/templates/my_profile.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load user_tags %}

{% block content %}
<section class="top-headless-margin">
	<div class="container">
		<div class="row">
			<div class='col-6 offset-3'>
				<h3 class='section-title'>My Profile</h3>
				{% include 'avatar/add.html' %}
				<form action="https://form.jotform.com/201397486796170" method="get" target="_blank">
					<button style="margin-bottom: 1em; font-weight: 900;" class='btn btn-block btn-primary' type="submit">Update profile</button>
				</form>
			
				<form method="post" enctype="multipart/form-data">
  				  {% csrf_token %}
  					{{ user_form|crispy }}									
  					{{ details_user_form|crispy }}
					{% if request.user|has_group:"update_group" %}
    				<input class='btn btn-block btn-primary' 
						type="submit" value="Update" />
					{% endif %}
				  </form>				
			</div>
		</div>
		<hr/>
		<div class='row'>
			<div class='col-12 text-center'>
			{% if request.user|has_group:"update_group" %}
				<p>Or cancel and go back to your <a href="/">Dashboard</a></p>
			{% else %}
				<p>Go back to your <a href="{% url 'dashboard' %}">Dashboard</a></p>
			{% endif %}
			</div>
		</div>
	</div>
</section>

{% endblock %}

thoughtmuseum_app/templates/portfolio.html
{% extends "index.html" %}
{% load static %}


{% block content %}
<header id="dashboard">
  <div class="container">
      <div class="row text-center">
			<div class='col-12'>
				<h3 class="text-center">Under construction</h3>
                <img class="center-block" src="{% static 'img/under_construction.jpeg' %}" >
			</div>
      </div>
  </div>
</header>

{% endblock %}